# Kustomization file to manage the base manifests
resources:
  - deployment.yaml
  - service.yaml

namePrefix: my-app-
namespace: my-app # ensure namespace is my-app

commonLabels:
  app: my-app

# Remove images section if not needed, or update image name/tag if required
# images:
#   - name: my-app
#     newName: my-docker-repo/my-app
#     newTag: latest