# This is a Kustomize configuration file.
# It tells Kustomize (and ArgoCD) which resources to deploy and how to customize them.
resources:
  - deployment.yaml # Deploy the Deployment resource
  - service.yaml    # Deploy the Service resource

namePrefix: my-app- # Add this prefix to all resource names (e.g., my-app-my-app)
namespace: my-app   # All resources will be deployed to the my-app namespace

commonLabels:
  app: my-app # Add this label to all resources for easy selection

# The images section can be used to override image names/tags if needed.
# Uncomment and edit if you want to use a custom image.
# images:
#   - name: my-app
#     newName: my-docker-repo/my-app
#     newTag: latest