apiVersion: v1
kind: Service
metadata:
  name: my-argocd-app
  labels:
    app: my-argocd-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: my-argocd-app
---
# This Service exposes the app internally in the cluster
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP